version: '3'

tasks:
  full-redeploy:
    cmds:
      - docker compose build
      - docker compose down -v
      - docker compose up --build --detach
  # TODO: make it work with any service
  rollout-mw:
    cmds:
      - docker compose build mediawiki
      - docker rollout mediawiki -t 120
  stop: docker compose stop
  teardown: docker compose down -v
  down: docker compose down
  # TODO: make it work with any service
  # TODO: make container indexes work too
  mw-bash: docker compose exec mediawiki /bin/bash
  maintenance-update:
    cmds:
      - docker compose exec mediawiki echo "$PWD"
      - docker compose exec mediawiki php var/www/html/w/maintenance/run.php update --quick
  up: docker compose up --detach
  up-preserve: docker compose up
  start: docker compose start --detach
  start-preserve: docker compose start
  restart:
    cmds:
      - docker compose stop
      - docker compose up --detach
  logs: docker compose logs -f
  # Maintenance scripts
  init-elastic: docker compose exec mediawiki sh ./init_elastic.sh
  init-sitemap:
    cmds:
      - task: mw-maintenance
        vars: {
          CLI_ARGS: generateSitemap --memory-limit=50M --fspath=/var/www/html/sitemap --identifier=monowheel.wiki --urlpath=/sitemap/ --server=https://monowheel.wiki --compress=yes --skip-redirects
        }
  init:
    cmds:
      - task: init-elastic
      - task: init-sitemap
  mw-maintenance: docker compose exec -it -w /var/www/html/w/ mediawiki php maintenance/run.php -- {{.CLI_ARGS}}
  download-map: curl -o map.osm.pbf https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
