<?php
namespace MediaWiki\Extension\Shubara\Tags;

/**
 * Makes pages in any namespace be able to be "autogenerated".
 *
 * In all seriousness, it's just used as an "outlet" for Shubara to control how any
 * page looks. It's normal usage is supposed to be only having an autogen tag as content
 * for the page, except for all the magic words and stuff. Shubara then handles everything
 * else.
 */
class Autogen {
    public static function run($input, array $args, Parser $parser, PPFrame $frame): string {

    }
}
