#!/bin/bash

RUN_JOBS="$MW_HOME/maintenance/run.php"

# Job types that need to be run ASAP no matter how many of them are in the queue
# Those jobs should be very "cheap" to run
php $RUN_JOBS runJobs --maxtime=3600 --type="enotifNotify"
# Everything else, limit the number of jobs on each batch
php $RUN_JOBS runJobs --maxtime=3600 --maxjobs=40

touch /tmp/mw/jobrunner
